import type { IconType } from "react-icons"
import {
  SiPython,
  SiRust,
  SiFastapi,
  SiDjango,
  SiPostgresql,
  SiSqlite,
  SiDocker,
  SiTerraform,
  SiGooglecloud,
  SiLinux,
  SiNextdotjs,
  SiReact,
  SiSvelte,
  SiTypescript,
  SiTailwindcss,
  SiShadcnui,
  SiGithub,
  SiTauri,
  SiPostman,
  SiSwagger,
  SiClaude,
} from "react-icons/si"
import { Webhook, Code2, type LucideIcon } from "lucide-react"

export const SKILL_ICONS: Record<string, IconType | LucideIcon> = {
  "Google Cloud Platform (GCP)": SiGooglecloud,
  Terraform: SiTerraform,
  Docker: SiDocker,
  "Linux/Bash": SiLinux,
  Python: SiPython,
  Rust: SiRust,
  FastAPI: SiFastapi,
  Django: SiDjango,
  PostgreSQL: SiPostgresql,
  SQLite: SiSqlite,
  "RESTful APIs": Webhook,
  "Next.js": SiNextdotjs,
  React: SiReact,
  Svelte: SiSvelte,
  TypeScript: SiTypescript,
  "Tailwind CSS": SiTailwindcss,
  "Shadcn UI": SiShadcnui,
  "Git & GitHub": SiGithub,
  Tauri: SiTauri,
  Postman: SiPostman,
  "Swagger/OpenAPI": SiSwagger,
  "VS Code": Code2,
  "Claude Code": SiClaude,
}
